resolver: lts-10.7

packages:
- lndr-backend/
- lndr-cli/
- location:
    git: https://github.com/aupiff/hs-web3.git
    commit: 08fe2fdd6a61ac1300d643995b27a42865fe455f
  extra-dep: true
- location:
    git: https://github.com/aupiff/ethereumhs-util.git
    commit: 0a187b13db9199dfb92e2124c9b4ca2ebf2c6549
  extra-dep: true

extra-deps:
- HUnit-1.6.0.0
- aeson-1.2.4.0
- amazonka-1.5.0
- amazonka-s3-1.5.0
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- bimap-0.3.3
- cmdargs-0.10.20
- configurator-0.3.0.0
- cryptonite-0.24
- data-default-0.7.1.1
- dhall-1.8.0
- either-4.5
- emailaddress-0.2.0.0
- equational-reasoning-0.5.0.0
- fast-logger-2.4.11
- ghc-typelits-presburger-0.1.1.1
- hashable-1.2.6.1
- http-client-0.5.10
- http-conduit-2.2.4
- http-types-0.9.1
- lens-4.15.4
- list-t-1.0.0.1
- listsafe-0.1.0.1
- memory-0.14.11
- monomorphic-0.0.3.3
- mtl-2.2.1
- postgresql-simple-0.5.3.0
- presburger-1.3.1
- pretty-simple-2.0.2.0
- relapse-1.0.0.0
- resource-pool-0.2.3.2
- resourcet-1.1.11
- scientific-0.3.5.2
- secp256k1-0.5.2
- servant-0.11
- servant-docs-0.11
- servant-server-0.11.0.1
- sized-0.2.1.1
- stm-2.4.5.0
- text-1.2.2.2
- type-natural-0.7.1.4
- unordered-containers-0.2.8.0
- wai-3.2.1.1
- wai-logger-2.3.1
- warp-3.2.13
- warp-tls-3.2.4
