resolver: lts-10.7

packages:
- lndr-backend/
- lndr-cli/
- location:
    git: https://github.com/aupiff/hs-web3
    commit: 08fe2fdd6a61ac1300d643995b27a42865fe455f
  extra-dep: true
- location:
    git: https://github.com/aupiff/ethereumhs-util
    commit: 0a187b13db9199dfb92e2124c9b4ca2ebf2c6549
  extra-dep: true

extra-deps:
- equational-reasoning-0.5.0.0
- dhall-1.8.0
- ghc-typelits-presburger-0.1.1.1
- monomorphic-0.0.3.3
- presburger-1.3.1
- relapse-1.0.0.0
- secp256k1-0.5.2
- sized-0.2.1.1
- type-natural-0.7.1.4
